# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "bank-actor.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "bank-actor.dll"]

# Build Image
# docker build --rm -f Dockerfile -t bank-actor .
# docker run -it --rm -p 5052:80 bank-actor

# docker tag bank-actor arambazamba/bank-actor
# docker push arambazamba/bank-actor

# Injecting environment variables into the container
# docker run -it --rm -p 5052:80 bank-actor -e "CosmosDB:InitCosmosClient=false"

# Browse using: 
# http://localhost:5052
# http://localhost:5052/config
