@ordersUrl = https://localhost:5002

@customerId = 1

### Add new order
# @name order
POST {{ordersUrl}}/orders/create HTTP/1.1
content-type: application/json

{    
    "customerId": "{{customerId}}",
    "type": "order",
    "total": 18,
    "customer": {
        "name": "Alexander Pajer",
        "email": "alexander.pajer@integrations.at",
        "address": "Am Himmel, 1190 Wien, Austria"
    },
    "payment": {
        "type": "Credit Card",
        "account": "**** **** **** 1234"
    },
    "items": [
        {
            "id": 2,
            "name": "Blini with Salmon",
            "price": 9,
            "quantity": 2
        }
    ]
}

### Get all documents of type order
GET {{ordersUrl}}/orders/getAll HTTP/1.1
content-type: application/json

### Get order by id
GET {{ordersUrl}}/orders/getById/1/1 HTTP/1.1
content-type: application/json

### Update order
PUT {{ordersUrl}}/orders/update HTTP/1.1
content-type: application/json

{
    "id": "c9ff7eb1-01ca-47f0-b147-15debbf01023",
    "customerId": "1",
    "type": "order",
    "total": 18,
    "customer": {
        "name": "Alexander Pajer",
        "email": "alexander.pajer@integrations.at",
        "address": "Hauptstraße 1, Wien, Austria"
    },
    "items": [
        {
            "id": 2,
            "name": "Schnitzel",
            "price": 9,
            "quantity": 2
        }
    ],
    "Events": null,
    "CanceledByUser": null
}

