# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "food-mvc-dapr.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "food-mvc-dapr.dll"]

# Build Image
# docker build --rm -f dockerfile -t food-mvc-dapr .

# Run Image without env vars
# docker run -it --rm -p 5051:80 food-mvc-dapr

# Browse using: 
# http://localhost:5051/

# Publish Image to dockerhub
# docker tag food-mvc-dapr arambazamba/food-mvc-dapr
# docker push arambazamba/food-mvc-dapr