# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "delivery-service.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "delivery-service.dll"]

# Build Image
# docker build --rm -f Dockerfile -t delivery-service .
# docker run -it --rm -p 5057:80 delivery-service

# docker tag delivery-service arambazamba/delivery-service
# docker push arambazamba/delivery-service

# Injecting environment variables into the container
# docker run -it --rm -p 5051:80 delivery-service -e "App__2__AuthEnabled"="false"

# Browse using: 
# http://localhost:5054
