# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "graph-notification-service.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "graph-notification-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t graph-notification-service .
# docker run -it --rm -p 5058:80 graph-notification-service

# docker tag graph-notification-service arambazamba/graph-notification-service
# docker push arambazamba/graph-notification-service

# Injecting environment variables into the container
# docker run -it --rm -p 5058:80 graph-notification-service -e "GraphCfg:ClientSecret=cez8Q~YN3BCUROOC35.FmYiixCgxtalUISBy3dyc"

# Browse using: 
# http://localhost:5051
# http://localhost:5051/food
# http://localhost:5051/env