@paymentsUrl = http://localhost:7074

### deposit to account
POST {{paymentsUrl}}/api/bankAccount/updateBalance/9876/1000

### withdraw from account
DELETE {{paymentsUrl}}/api/bankAccount/updateBalance/9876/200

### get account status
GET {{paymentsUrl}}/api/bankAccount/getBalance/9876

### execute payment exceeding account balance
POST {{paymentsUrl}}/api/bankAccount/processPayment
content-type: application/json

{
    "id":"68a2849e-46d6-44ed-a5dc-ca22e8210e6e",
    "orderId":"ce911547-42e1-488c-8ea8-b1553ac8e20c",
    "customerId":"5",
    "eventType":"PaymentRequested",
    "data":"{
        \"orderId\":\"ce911547-42e1-488c-8ea8-b1553ac8e20c\",
        \"amount\":48.0,
        \"paymentInfo\": {
            \"name\":\"Marcela Tatra\",
            \"type\":\"Bank Transfer\",
            \"accountNumber\":\"9876\"
            }
    }",
    "timestamp":"2023-11-07T10:34:04.6723628Z"
}
