@ordersUrl = https://localhost:5002
@customerId = 1

### Add new order
# @name order
POST {{ordersUrl}}/orders/create HTTP/1.1
content-type: application/json

{    
    "customerId": "{{ customerId }}",
    "type": "order",
    "total": 18,
    "customer": {
        "name": "Alexander Pajer",
        "email": "alexander.pajer@integrations.at",
        "address": "Am Himmel, 1190 Wien, Austria"
    },
    "payment": {
        "type": "Credit Card",
        "account": "**** **** **** 1234"
    },
    "items": [
        {
            "id": 2,
            "name": "Blini with Salmon",
            "price": 9,
            "quantity": 2
        }
    ]
}

### Add payment request
POST {{ordersUrl}}/orders/add HTTP/1.1
content-type: application/json

{
    "orderId": "{{ order.response.body.id }}",
    "customerId": "{{ customerId }}",
    "eventType": "PaymentRequested",
    "eventData": {
        "amount": 55,
        "payment": {
            "type": "Credit Card",
            "account": "**** **** **** 1234"
    	}
    }
}

### Confirm payment request
POST {{ordersUrl}}/orders/add HTTP/1.1
content-type: application/json

{
    "orderId": "{{ order.response.body.id }}",
    "customerId": "{{ customerId }}",
    "eventType": "PaymentSuccess",
    "eventData": {
        "id": "b80b6d7a-0075-4eff-82e9-1c26126f598d",
        "customerId":"{{ customerId }}",
        "amount": 55,
        "payment": {
            "type": "Credit Card",
            "account": "**** **** **** 1234"
    	}
    }
}
